### ISSUE TITLE
Add please cvar sm_rebel_enable, need to disable sm_r sm_rebel commands

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#10]
For Example https://github.com/KissLick/TeamGames/blob/67773bbf351c904449037b2b38742a4885db5155/addons/sourcemod/scripting/Commands.sp#L283
```javascript
public Action:Command_Rebel(iClient, iArgs)
{
	if (Client_IsValid(iClient)) {
		if (CVAR == 0) {
			CPrintToChat(iClient, "%t", "Rebel-IsDisabled");
		} else if (GetClientTeam(iClient) != CS_TEAM_T) {
			CPrintToChat(iClient, "%t", "Rebel-PrisonersOnly");
		} else if (!IsPlayerAlive(iClient)) {
			CPrintToChat(iClient, "%t", "Rebel-AliveOnly");
		} else if (!TG_IsPlayerRedOrBlue(iClient)) {
			CPrintToChat(iClient, "%t", "Rebel-InTeamOnly");
		} else {
			MakeRebel(iClient);
		}
	}

	return Plugin_Handled;
}
```
And new key "2" for tg_game_rebelattack
// Action taken when red/blue T attack CT during game
// 	0 = no dmg & no rebel
// 	1 = no dmg & make rebel
// 	2 = dmg & no rebel

**Comment by SHAREN** [comment]
Or how to make so that during games T could kill CT?

**Comment by KissLick** [comment]
1. Why do you want to disable sm_rebel? I think prisoners should have a "thing" how to rebel against TeamGames. Now this command allows prisoners to leave team and even leave game, so they can rebel.

2. Why do you want to allow prisoners to attack wardens during game? I think it unfair because prisoners get weapons for game and I can easily imagine what would happen if you start Machines + 500HP...

I just don't see the point here...

**Comment by SHAREN** [comment]
Because CT when no admins specifically activated games that T could not rebel

**Comment by KissLick** [comment]
Well, then it's problem originating from rules and their breaking. Anyway, prisoners can use command sm_rebel to leave team/game.

You also might set cvar `tg_menu _percent` to partialy avoid that problem.

Or I can create some "time lock" module which would disable tg games for first N seconds of each round.

**Comment by KissLick** [comment]
Time lock is on my TODO list now.

**Comment by KissLick** [comment]
Time lock done - https://github.com/KissLick/TeamGames/commit/7790b32a248ffa49d36b539c485e44d0568fafb2
