### ISSUE TITLE
Module Team Games is also a module for LR (Hosties2)

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#11]
For example, these games also would be very useful in LR
TG_ChickenHunt.sp
TG_GunFight.sp
TG_HEGrenades.sp
TG_HeadShotOnly.sp
TG_HotPotato.sp
TG_Machines.sp
TG_ReloadBattle.sp
TG_TaserMania.sp
Or please do based on these plug-ins for standalone HOSTIES2

**Comment by KissLick** [comment]
I don't plan on making TeamGames games working with Hosties. You can do it yourself or ask someone else.
