### ISSUE TITLE
!refuse

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#12]
The preparation of the game is given 5 seconds, and if T during the preparation time to write "!refise" or "-" the game does not start.

It is necessary that T could protect themselves from CT that launch games that T could not attack them.

**Comment by KissLick** [comment]
Why do you want to add new command if there is already sm_rebel which does this and even more?
By the way, if you insist on this. You can create very simple module doing this.

**Comment by SHAREN** [comment]
OK, it's idea
