### ISSUE TITLE
HotPotato Issues

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#13]
1)
https://github.com/KissLick/TeamGames/blob/master/addons/sourcemod/scripting/modules/TG_HotPotato.sp

The game HotPotato after the death of a HotPotatoplayer a bomb is not removed, but new hot potato is created. As a result, it created a lot of bombs, and it is not clear which of the bombs is a hot potato.

2)
It would be nice to make a bomb, which has a model of a hot potato
for example:
```javascript
SetEntityModel(bomb_ent, "HotPotatoModel");
```
Where HotPotatoModel == models\props_junk\watermelon01.mdl or models\props_misc\bread-4.mdl or models\gibs\hgibs.mdl for exapmle

3)
And that from the hot potato to the "holder" of potatoes was a line
```javascript
TE_SetupBeamPoints (posHotPotato, posHolder, ...........);
TE_SendToClient (allclients);
```

**Comment by KissLick** [comment]
1 - Gonna have a look at that, when I tested this game everything was OK

2 - That crossed my mind when I was making that game -> goes on my TODO list

3 - Good idea -> goes on my TODO list

**Comment by KissLick** [comment]
1 - Worked fine with bots on local server
2 - Done
3 - Done

It needs some polishing but it should work as it is now. Can you add me on [Steam](steamcommunity.com/id/kisslick), so I can send you testing version?

**Comment by KissLick** [comment]
Done - https://github.com/KissLick/TeamGames/commit/5202fe2299716c79f33e6c6b0b227d064c752c3f
