### ISSUE TITLE
FenceCorner model scale

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#14]
I use  another model  Fence corner (line_post.mdl), it is the standard cs:go and does not require downloading, but a little low. So please add
[FenceCorner <float: scale>] models/props_unique/airport/line_post.mdl
http://linkme.ufanet.ru/images/9656fb9cc783df3273a68ad8b3caa558.jpg

**Comment by KissLick** [comment]
What do you mean by (bellow)?
> So please add [FenceCorner] models/props_unique/airport/line_post.mdl

Do you mean that little gap above your model? So you are just asking me to add a way how to adjust rope heights?

**Comment by SHAREN** [comment]
Oh sorry

**Comment by KissLick** [comment]
And that should scale the model? As far as I know, there is no way, how to scale model in-game... :-/

**Comment by SHAREN** [comment]
Like this 
SetEntPropFloat(client, Prop_Send, "m_flModelScale", fScale);
https://forums.alliedmods.net/showthread.php?p=1774605 possibly?

**Comment by KissLick** [comment]
Already tried, but it didn't work...
https://forums.alliedmods.net/showthread.php?t=274867
