### ISSUE TITLE
translations ru

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#16]
https://github.com/KissLick/TeamGames/blob/master/addons/sourcemod/translations/ru/TeamGames.phrases.txt#L166
Not О**тc**ановить игру
О**ст**ановить игру

**Comment by KissLick** [comment]
I got some work with marks now, so I will fix this in a few days (hopefully).

**Comment by KissLick** [comment]
Done - https://github.com/KissLick/TeamGames/commit/d16a4a1d2f01f1c45447732b38e3b45cef4d975d ;-)
