### ISSUE TITLE
All CTs can create marks

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#17]
tgm_warden_admins                        : 1        :                  : Treat admins as warden.
tgm_warden_fences                        : 1        :                  : Only warden can use TG fence.
tgm_warden_games                         : 1        :                  : Only warden can use TG games.
tgm_warden_marks                         : 1        :                  : Only warden can use TG marks.
tgm_warden_menu                          : 1        :                  : Only warden can use TG menu.
tgm_warden_teams                         : 1        :                  : Only warden can use TG teams.

**Comment by KissLick** [comment]
I believe that if you set cvar `tgm_warden_marks 0` all CTs can create marks.

**Comment by SHAREN** [comment]
it is necessary that only the commander could put markers

**Comment by KissLick** [comment]
So the problem is that `tgm_warden_marks 1` doesn't work?

I am gonna test as soon as I update my server.

**Comment by KissLick** [comment]
Just tested and it seems to work fine. What is your `tgm_warden_admins` value? Are you sure that admins don't "overrule" warden only?

Anyway I am gonna change cvars so you can set it to:
`0` = Everyone can use
`1` = Only warden can use
`2` = Only warden and admins with access to `sm_teamgames` can use

**Comment by SHAREN** [comment]
Thank you, the problem is solved, but it would be even better if other CT (no warden) could do a different color sprays. For example warden in blue, others CT - green
