### ISSUE TITLE
Invisible players in HotPotato

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#18]
I think that you need to install the Alpha 255
https://github.com/KissLick/TeamGames/blob/2d77236f9cc055ae1d03849afa1230d16dca3022/addons/sourcemod/scripting/modules/TG_HotPotato.sp#L223 for example.

P.S. and _**sm plugins reload TeamGames/TG_HotPotato**_ crash server.

**Comment by KissLick** [comment]
Thx, gonna fix that soon :-)

**Comment by KissLick** [comment]
Fixed - https://github.com/KissLick/TeamGames/commit/3f9b5088be1b9f9b4f69450ad7f96543c8392d67
