### ISSUE TITLE
DOWNLOAD_HEALTHBAR "HotPotato-healthbar" not working

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#19]
L 05/02/2016 - 04:34:19: [TeamGames/TeamGames.smx] Unknown file prefix "HotPotato-healthbar" (file: "materials/tg/healthbar/100.vmt") !
L 05/02/2016 - 04:34:19: [TeamGames/TeamGames.smx] Unknown file prefix "HotPotato-healthbar" (file: "materials/tg/healthbar/90.vmt") !
L 05/02/2016 - 04:34:19: [TeamGames/TeamGames.smx] Unknown file prefix "HotPotato-healthbar" (file: "materials/tg/healthbar/70.vmt") !
L 05/02/2016 - 04:34:19: [TeamGames/TeamGames.smx] Unknown file prefix "HotPotato-healthbar" (file: "materials/tg/healthbar/50.vmt") !
L 05/02/2016 - 04:34:19: [TeamGames/TeamGames.smx] Unknown file prefix "HotPotato-healthbar" (file: "materials/tg/healthbar/30.vmt") !
L 05/02/2016 - 04:34:19: [TeamGames/TeamGames.smx] Unknown file prefix "HotPotato-healthbar" (file: "materials/tg/healthbar/10.vmt") !

https://github.com/KissLick/TeamGames/search?utf8=%E2%9C%93&q=DOWNLOAD_HEALTHBAR

**Comment by KissLick** [comment]
Oh yeah, I removed HealthBar from `HotPotato` and added it as a core feature.
Just use `[HealthBar <10, 20, ... 100>]` and it's gonna work for majority of the games.

I forgot to remove this define from `HotPotato` and upload new HealthBar materials - goes on my TODO list.
