### ISSUE TITLE
tg_fence_type 2 is invisible

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#2]
shadows of his fall, but it is invisible http://linkme.ufanet.ru/images/c42aceb70abc183da3c9b03700826396.jpg

tg_fence_type 1 working fine

P.S. how to make that Prisoners could not pass through it?

**Comment by KissLick** [comment]
I am gonna have a look at that and I will let you know more after that.

1. Are you sure you have properly set download prefix `[FenceMaterial]`?
2. What material do you use for `[FenceMaterial]`?

Thx for your report! ;-)

**Comment by SHAREN** [comment]
[FenceMaterial 1.0 255 255 255 255] materials/cable/bf_rope.vmt
materials/cable/bf_rope.vtf

When tg_fence_type 1 ring is operating normally, see the color is not black rope

**Comment by KissLick** [comment]
Seems like there is problem with shareds used by materials...

If I use shader `SplineRope` which is used by ropes in Source engine and `tg_fence_type 2`, it´s not rendered during "building" fence (here it's beam and not rope).

If I use another shader it works for `tg_fence_type 1` but not `tg_fence_type 2`.

**Summary:** We have to have two different materials, one for beam fence and another one for rope fence... And I also have to somehow make visible beam when "building" rope fence (I guess hardcoded material).


And as for players not passing thru fence, now it's not possible. Now you can only punish them for escaping fence, but not prevent them from escaping. For that should be possible to make simple TG module to push players back to the fence (I might do that).

**Comment by SHAREN** [comment]
It would be great if you so make (push players back), but that the prisoners remained opportunity to jump the fence and run away.

**Comment by SHAREN** [comment]
Setting CBaseEntity to non-brush model models/props/cs_office/trash_can.mdl
Setting CBaseEntity to non-brush model models/props/cs_office/trash_can.mdl
Setting CBaseEntity to non-brush model models/props/cs_office/trash_can.mdl
Setting CBaseEntity to non-brush model models/props/cs_office/trash_can.mdl
In server console
https://github.com/KissLick/TeamGames/search?utf8=%E2%9C%93&q=trash_can.mdl

**Comment by KissLick** [comment]
As far as I know, that is something we cannot solve...

**Comment by KissLick** [comment]
Fixed - https://github.com/KissLick/TeamGames/commit/c992773436de06655f535a1c92ec62aebdb73514

**Comment by SHAREN** [comment]
When you create a ring material is changed, but Finished ring does not work
http://images.akamai.steamusercontent.com/ugc/392175615068918402/4675C4DA2AACA6E2F8CD07F32896923A513542E7/ not workink with tg_fence_type 2, I think problem is here https://github.com/KissLick/TeamGames/blob/c992773436de06655f535a1c92ec62aebdb73514/addons/sourcemod/scripting/LaserFences.sp#L139

**Comment by KissLick** [comment]
Post here your material's `vmf` file pls (as attachment).

**Comment by SHAREN** [comment]
"Unfortunately, we don’t support that file type. "
http://rghost.ru/8JjmphwNX from here https://github.com/KissLick/TeamGames/tree/master/extras/rope

**Comment by KissLick** [comment]
The shader in this material is `UnlitGeneric` which is currently unsupported by ropes (since some CS:GO update). You need to use material with shader `SplineRope` if you want to use rope fences.

You can simply create your own version of this material, just with shader `SplineRope` (differs only in `vmt` file).

[Wiki explenation - Note #1](https://github.com/KissLick/TeamGames/wiki/Fences#note-1)
