### ISSUE TITLE
tg_noneteam_attack

### ISSUE THREAD

**Issue by shanapu** [KissLick/TeamGames#20]
i would be happy with a new ConVar. something like:
`tg_noneteam_attack - Can Ts in **none team** attack each other even if there is no game?`
I misread alltime `tg_team_attacks` "excluding". Would be very helpful for my project. 
Thanks in advance!

**Comment by KissLick** [comment]
Yep, goes on my TODO list.

**Comment by KissLick** [comment]
Done - https://github.com/KissLick/TeamGames/commit/310479dcd9c0b67a2059705d2b900715c6d75c15
