### ISSUE TITLE
confirmation to play

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#21]
So my jail is set up so that if no CT, the cells are always open and always T respawned.
And at this time when there is no CT admins can run games.
Can you do cvar to the T came out menus (if he wants to play the game)
At the moment when the admin puts the player in the team.
Sorry for bad English.

**Comment by KissLick** [comment]
Hallo,

I am not gonna add this into the core. Prisoners can use command `!rebel` to leave a team.
However, I made for you a little plugin which should do what you seek. I didn't test it, so there might be some bugs... Feel free to let me know.

https://gist.github.com/KissLick/c0f11e8a94211fa096bf7d41b42f017e

**Comment by SHAREN** [comment]
Thank you!
