### ISSUE TITLE
Native "RemoveEdict" reported: Edict 1107 (1107) is not a valid edict

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#22]
```
[SM] Native "RemoveEdict" reported: Edict 1107 (1107) is not a valid edict
[SM] Displaying call stack trace for plugin "TeamGames/TeamGames.smx":
[SM]   [0]  Line 96, HealthBar.sp::RemoveHealthBar()
[SM]   [1]  Line 45, HealthBar.sp::UpdateHealthBar()
[SM]   [2]  Line 365, TeamGames.sp::Hook_OnTakeDamagePost()
```
the game is that the healthbars remain after the game

**Comment by KissLick** [comment]
Unfortunately, I was not able to replicate this issue. Just to clarify, as far as I understand it. The healthbars remain after game end and gives this error?

1. How often does this occure?
1. Are the visible healthbars still attached to the players or just hanging in the air?
1. Did happen something special? (e.g. player disconnected during game)
1. Are you using the latest version of TeamGames - `0.16.1.1` ?

The more details you give me about this issue, the more likely I will be able to fix it.

**Comment by SHAREN** [comment]
4 Again confused with git
updated, let's see what will now be

**Comment by KissLick** [comment]
I added check for entity validity in https://github.com/KissLick/TeamGames/commit/884490516675defccb1ab1a68bfc58a73211fb0b so please try now.

Unfortunately I still wasn't able to replicate this bug... Does this happen everytime TG creates healthbars?
