### ISSUE TITLE
Client index -1 is invalid 

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#24]
I think in https://github.com/KissLick/TeamGames/blob/f791bbd0ad2ae969bd67c1802b4968ed1221a037/addons/sourcemod/scripting/modules/TG_Warden.sp#L107
need to add 
if (....&& **iClient > 0** && warden_iswarden(iClient))
        return true;

because
> [SM] Exception reported: Client index -1 is invalid
> [SM] Blaming: sm_jail_csgowarden.smx()
> [SM] Call stack trace:
> [SM]   [0] IsClientInGame
> [SM]   [1] Line 448, /home/home/GIT/sm_warden/scripting/sm_jail_csgowarden.sp::Native_IsWarden()
> [SM]   [3] warden_iswarden
> [SM]   [4] Line 107, /home/home/GIT/TeamGames/addons/sourcemod/scripting/modules/TG_Warden.sp::CheckWardenAccess()
> [SM]   [5] Line 74, /home/home/GIT/TeamGames/addons/sourcemod/scripting/modules/TG_Warden.sp::TG_OnPlayerTeam()
> [SM]   [7] Call_Finish
> [SM]   [8] Line 158, Teams.sp::SwitchToTeam()
> [SM]   [9] Line 362, Teams.sp::ClearTeam()
> [SM]   [10] Line 125, Api.sp::Native_ClearTeam()
> [SM]   [12] TG_ClearTeam
> [SM]   [13] Line 120, /home/home/GIT/t2_lr_cfg/addons/sourcemod/scripting/jail_t2lrcfg.sp::lr()

**Comment by KissLick** [comment]
Do I understand it correctly, that you tried to use `TG_ClearTeam` in `jail_t2lrcfg.sp` ?

Anyway, I think I know where is the problem and I am gonna fix it as soon (now I have some unfinished DocParser changes) as possible.

**Comment by SHAREN** [comment]
I have long been using TG_ClearTeam in jail_t2lrcfg.sp but the error saw just now.
I certainly already corrected if (i Client> 0) in my plugin warden, but "-1" I think it should not have been

**Comment by KissLick** [comment]
That `-1` in client variable is because `TG_ClearTeam` calls switch player team function with `-1` as activator. I am gonna add check for non-valid client in Warden module, that should solve it properly.

**Comment by KissLick** [comment]
Should be done - https://github.com/KissLick/TeamGames/commit/86a1876f4132cc75f639cfe41d06e7433f87e6d7
