### ISSUE TITLE
emergency StopGame

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#25]
Please do so that CT can quickly and emergency stop the game.

ForExample sm_stopgame or with Bind-actions

**Comment by KissLick** [comment]
Right now CTs can stop game with `Core_StopGame` in TG menu or Bind actions.
Admins can also stop game with command `sm_stoptg`.

I can change `sm_stoptg` to be public (non-admin) command and add it to Warden module if you want.

**Comment by SHAREN** [comment]
and In addition to all message when CT starts the game, about how he can quickly stop the game

**Comment by KissLick** [comment]
Should be done - https://github.com/KissLick/TeamGames/commits/master

Please test it (I did only a very short test).
