### ISSUE TITLE
addons/sourcemod/plugins Missing?

### ISSUE THREAD

**Issue by Some0ne1337** [KissLick/TeamGames#26]
I can't find addons/sourcemod/plugins . Is it missing or am I just dumb?

**Comment by KissLick** [comment]
No :-D you are not dumb. TeamGames has yet to be released (**I hope it's gonna be soon**).

For now, you have to compile it by yourself. it's pretty easy, just download TeamGames, few includes (some includes are here on my GitHub) and you are ready to compile.

**Comment by Some0ne1337** [comment]
Okay thank you, i will wait because I cant compile it; getting error "cant read from clients.inc" even when I got them, so nvm, I will wait :D ;)

**Comment by KissLick** [comment]
I will resolve the last remaining bug and then I am gonna compile TeamGames and give it to you.

**Comment by KissLick** [comment]
Sorry that it took so long... I hope it's gonna be OK, if you find any bug pls issue it.

Download: https://www.dropbox.com/sh/d5jgl368e7yjf5c/AAAAa5w4DatT_hnXdmurNG_ka?dl=0

**Comment by Some0ne1337** [comment]
Hey! We tried to compile teamgames.sp but we are getting this error.

SourcePawn Compiler 1.9.0.5921
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

extra/smlib.inc(8) : fatal error 183: cannot read from file: "smlib/general"

Compilation aborted.
1 Error.

Could you please compile teamgames.sp for us? Thank you anyway! :)

**Comment by KissLick** [comment]
Sorry I forgot to include `TeamGames.smx`.

It's in there now.
