### ISSUE TITLE
RequestFrame2 error 130: cannot coerce functions to values on sm 1.8.0.5914

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#27]
```
SourcePawn Compiler 1.8.0.5914
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

/home/home/scripting/include/teamgames-stocks.inc(269) : error 130: cannot coerce functions to values
/home/home/scripting/include/teamgames-stocks.inc(280) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future
```

After https://github.com/KissLick/TeamGames/commit/770fdedd0b602c38ff23ca1746562417d18a243c

**Comment by KissLick** [comment]
This might (very likely) need to be rewritten to the new syntax.

This is not my priority right now (but I will make TG compatible with 1.8+ compiler). Please use older compiler for now and you won't have this problem.
I use compiler version `SourcePawn Compiler 1.6.0-dev+c744b39` (yeah, still that old one O:-) )

**Comment by KissLick** [comment]
Should be OK now - https://github.com/KissLick/TeamGames/commit/213546266272f6c8f5b4c155041b697c470c0468
