### ISSUE TITLE
[phrases]"{1} moved all players to red team!"  after "Everyone into Red team" 

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#28]
please do so when you move into the team, the message is dispatched to chat with one at all players, not for each player individually.
for example:
instead
sharen Player 1 moved in the red team
sharen Player 2 moved in the red team
sharen moved 3 player in the team red
sharen moved 4 player in the team red
do this way:
sharen moved all the players in the team red

I've already done the blank phrases:
```
	"PlayerMove-RedTeamALL" // msg for all players when player {1} moved all players to team red
	{
		"#format"	"{1:s}"
		"en"		"{1} moved all players to{tg-redteam} red {default} team!"
		"ru"		"{1} переместил всех в команду {tg-redteam} красных!"
	}
	"PlayerMove-FiftyFiftyAll" // msg for all players when player {1} moved all players to both teams
	{
		"#format"	"{1:s}"
		"en"		"{1} divided into 2 teams all!"
		"ru"		"{1} поделил всех на 2 команды!"
	}
	"PlayerMove-NoneTeamAll" // msg for all players when all players was moved out of any team
	{
		"en"		"All players expelled from the team!"
		"ru"		"Всех игроков исключили из команды!"
	}
```

P.S. and additionals for ru translation http://rgho.st/85PKkCkpX

**Comment by KissLick** [comment]
Goes on my TODO list, thx.

**Comment by KissLick** [comment]
Done - https://github.com/KissLick/TeamGames/commit/e31b61c777ba9769a5459de5c3cead21ea52babd, https://github.com/KissLick/TeamGames/commit/99f405d004b17776c4166a1fcb572fc4c792a551 and https://github.com/KissLick/TeamGames/commit/3ae4909e4901df3631237cf47f2d289e2a7e406e
