### ISSUE TITLE
Invalid client index 328 (IsPlayerAlive)

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#29]
```
[SM] Exception reported: Invalid client index 328
[SM] Blaming: TeamGames/TeamGames.smx()
[SM] Call stack trace:
[SM]   [0] IsPlayerAlive
[SM]   [1] Line 659, Api.sp::Native_StopGame()
[SM]   [3] TG_StopGame
[SM]   [4] Line 121, /home/home/GIT/t2_lr_cfg/addons/sourcemod/scripting/jail_t2lrcfg.sp::lr()
```

May be it is userid, not index? https://github.com/KissLick/TeamGames/blob/a6ae9825289e741ed65fc9f0b3bbf8ccf285cba4/addons/sourcemod/scripting/Api.sp#L659

**Comment by KissLick** [comment]
Should be done - https://github.com/KissLick/TeamGames/commit/255582a1e164cb9904bf53f948dc2bc54bf25fe3
