### ISSUE TITLE
Please add to Core_TeamsMenu function all in red paint and paint all the Red and Blue (50/50)

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#3]
And to Core_GamesMenu-Fifty Fifty and Core_GamesMenu-ReadOnly have always been active in menu, but if the team is not divided correctly, the plugin provides automatic distribution of either the Red team a half Red and Blue

**Comment by KissLick** [comment]
*Please add to Core_TeamsMenu function all in red paint and paint all the Red and Blue (50/50)* - I will add that on ConVar

*And to Core_GamesMenu-Fifty Fifty and Core_GamesMenu-ReadOnly have always been active in menu, but if the team is not divided correctly, the plugin provides automatic distribution of either the Red team a half Red and Blue* - I **might** add that on ConVar

Thx for your ideas! :-)

**Comment by SHAREN** [comment]
Thank you, this improvements  saves a lot of  time. because on my server guards very long versed in the menu and a few minutes of prisoners color

**Comment by KissLick** [comment]
Added: https://github.com/KissLick/TeamGames/commit/5bab6ab8916da5f6cbbad5a4801a4680ba0e98b0

**Comment by SHAREN** [comment]
thank you

**Comment by SHAREN** [comment]
Can you do that after you have MenuTeams-FiftyFiftyAll CMD automatically appears the menu with FiftyFifty games, and when you select MenuTeams-RedTeamAll  automatically appears the menu with RedTeam games

**Comment by KissLick** [comment]
Added - https://github.com/KissLick/TeamGames/commit/1f5f843f7462f987a3fbf5c38072c872665e8dea

Btw. next time please make new issue.

**Comment by SHAREN** [comment]
Thank you. OK
