### ISSUE TITLE
TeamGames.phrases.txt need to replace "en" to "ru"

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#32]
https://github.com/KissLick/TeamGames/blob/3ae4909e4901df3631237cf47f2d289e2a7e406e/addons/sourcemod/translations/ru/TeamGames.phrases.txt#L27 L31 L35

**Comment by KissLick** [comment]
Done - https://github.com/KissLick/TeamGames/commit/2eab5b9fd4268b8c4f840538fa9944be7e4e3566

Thx
