### ISSUE TITLE
support DevZones

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#4]
Please do (as a module) For CT could start the game only when all  T will be in a certain zone.
Because many CT start the game right away as a prisoner out of the cells, and can start playing even if one of the prisoners escaped. What could spoil the gameplay.

For example:
"TG_Zones"
{
    "ba_jail_electric_vip_v3"
     {
             "Football"   //The game can begin only when all the T will be in one of these zones
             "Gameroom"
     }
     "jb_map2"
     {
              "Gameroom"
     }
}

If a CT wants to play, and some of the prisoners had escaped, he leaves a message: "To start the game Take all the prisoners in one of these areas:
Football
Gameroom "
https://forums.alliedmods.net/showthread.php?p=2023591 DevZones
Of course, if the server admin is not lazy and will place the zone on each map.
A note the zone using Dev Zones is a case for 5 minutes

Or just before the game to check whether all the prisoners next to each other or someone escaped.

**Comment by KissLick** [comment]
If I am gonna do that module, I am not gonna do that in near future.
Wardens should behave like wardens...
