### ISSUE TITLE
Can't compile the updated plugin.

### ISSUE THREAD

**Issue by Hexer10** [KissLick/TeamGames#41]
Error logs (a lot): http://pastebin.com/8HRPJ3Lz

**Comment by SHAREN** [comment]
Update D:\My Profile\Desktop\Nuova cartella (2)\scripting\include\lastrequest.inc 
https://github.com/dataviruset/sm-hosties/blob/master/addons/sourcemod/scripting/include/lastrequest.inc

in the scripting folder to compile only one file TeamGames.sp
other files such as ModuleData.sp Chat.sp Api.sp need not be compiled

**Comment by PremyslTalich** [comment]
Have a look at this [compiling tut](https://github.com/KissLick/TeamGames/wiki/Installation-guide#compiling-teamgames)
