### ISSUE TITLE
Bug if you put * .sp file in a single folder

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#6]
In the folder "plugins" I sort of *.sp files in folders, especially the modules, if I put a plug-in or module folder sourcemod / plugins / TeamGames, the plug can not create the setting.
```javascript
[TeamGames/TG_ChickenHunt.smx] Cannot create file 'addons/sourcemod/configs/colorvariables/plugin.TeamGames/TG_ChickenHunt.cfg' !
```

**Comment by KissLick** [comment]
Solved - https://github.com/KissLick/TeamGames/blob/master/TODO.md

You just need to recompile TG with the latest ColorVariables version.
