### ISSUE TITLE
ColorVariables  is not have {lightblue} for CS:GO

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#7]
addons/sourcemod/configs/colorvariables/plugin.TeamGames.cfg
replace	"tg-blueteam"		"{lightblue}"
to	"tg-blueteam"		"{blue}" //for exapmle

Because https://github.com/KissLick/ColorVariables is not have lightblue for CS:GO

**Comment by KissLick** [comment]
Thx! ;-) I kinda forgot about that... - https://github.com/KissLick/TeamGames/commit/dce4cbd4d104878ccb0413034a929f872782e8ba
