### ISSUE TITLE
Game Preparation wish with the issue of weapons

### ISSUE THREAD

**Issue by SHAREN** [KissLick/TeamGames#8]
Do so in games weapons were issued at the expense of 3, not at the beginning of reference.
And so it turns out that the account of all the T 3 are targeting each other in the head.
Or is it better to the account of 3 players thawed, and a moment later they were given weapons.

**Comment by KissLick** [comment]
Not sure I fully understand you...

You mean like GunFight, HeadshotOnly and PistolZoomBattle give weapons in OnGameStart, but Machines, NoZoom and RealoadBattle give weapons in OnGamePrepare (5 seconds earlier)?

**Comment by SHAREN** [comment]
If that's the case I can make it same for all games and give weapons in OnGameStart (after the countdown).

Yes, It is necessary that the weapon was given after the countdown

**Comment by KissLick** [comment]
Done - https://github.com/KissLick/TeamGames/commit/2509df25091bbcc6068e72f9eb467dda0c2d5c05
